export const RESPONSES_WS_MAX_INBOUND_BYTES = 1_048_576
export const RESPONSES_WS_MAX_TURN_EVENT_BYTES = 16_777_216
export const RESPONSES_WS_MAX_OUTBOUND_FRAME_BYTES = 1_048_576
export const RESPONSES_WS_SEND_HIGH_WATER_BYTES = 1_048_576
export const RESPONSES_WS_DRAIN_TIMEOUT_MS = 5_000
export const RESPONSES_WS_MAX_LOCAL_STATE_BYTES = 8_388_608
export const RESPONSES_WS_LOCAL_STATE_TTL_MS = 300_000
export const RESPONSES_WS_MAX_LOCAL_STATES = 1
export const RESPONSES_WS_UNOBSERVABLE_LIFETIME_BYTES = 16_777_216
export const RESPONSES_WS_MAX_CONTROL_BYTES = 65_536
export const RESPONSES_WS_CLEANUP_TIMEOUT_MS = 25_000

export const utf8Bytes = (text: string): number => new TextEncoder().encode(text).byteLength
