export function performanceLabels(t: (key: string) => string) {
  return {
    ttftMs: t("dash.perf.ttftMs"),
    firstTextMs: t("dash.perf.firstTextMs"),
    upstreamTps: t("dash.perf.upstreamTps"),
    overallTps: t("dash.perf.overallTps"),
    totalMs: t("dash.perf.totalMs"),
    upstreamMs: t("dash.perf.upstreamMs"),
    generationMs: t("dash.perf.generationMs"),
    gapMs: t("dash.perf.gapMs"),
    maxGapMs: t("dash.perf.maxGapMs"),
    outputTokens: t("dash.perf.outputTokens"),
    reasoningTokens: t("dash.perf.reasoningTokens"),
    inputTokens: t("dash.perf.inputTokens"),
    cachedInputTokens: t("dash.perf.cachedInputTokens"),
    keyId: t("dash.perf.keyId"),
    incomingModel: t("dash.perf.incomingModel"),
    model: t("dash.perf.model"),
    upstream: t("dash.perf.upstream"),
    sourceApi: t("dash.perf.sourceApi"),
    targetApi: t("dash.perf.targetApi"),
    runtimeLocation: t("dash.perf.runtimeLocation"),
    inputBucket: t("dash.perf.inputBucket"),
    cacheStatus: t("dash.perf.cacheStatus"),
    reasoningEffort: t("dash.perf.reasoningEffort"),
    mode: t("dash.perf.mode"),
    outcome: t("dash.perf.outcome"),
    stream: t("dash.perf.stream"),
    sync: t("dash.perf.sync"),
    success: t("dash.perf.success"),
    error: t("dash.perf.error"),
    cancelled: t("dash.perf.cancelled"),
    unknown: t("dash.perf.unknown"),
    hit: t("dash.perf.hit"),
    miss: t("dash.perf.miss"),
  }
}
